function [SamplingRate, f] = read_spk(name)
% function [SamplingRate, f] = read_spk(name)
% reads sampling rate and matrix f from MF-Spectrum file "name"
%
% last change: 5/2000

[SampleZahl,SamplingRate,Offset,...
          Kanalanzahl,Kanalliste,KanalNr,...
          VoltageRange,Reserviert,...
          XachsSchriftLen,XachsSchrift,...
          YachsSchriftLen,YachsSchrift,...
          Rand,Cursor,LaufzeitKor,OberkantdB,...
          Dynamik,NulldBVolt,LeftCursor,...
          RightCursor,AddaIdentLen,AddaIdent,...
          KommentarLen,Kommentar,f] = itafread(name);